# mysql-Datenbank - docker-compose.yml
services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: geheim
        ports:
            - "3306:3306"
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysql